name: Node/Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.x

      - name: npm install, build, and test
        run: |
          export PATH=$HOME/.deno/bin:$PATH
          yarn
          yarn lint
          yarn test
        env:
          CI: true
